# Generated by Django 4.1.2 on 2022-11-16 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='O_direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.CharField(max_length=128)),
                ('organizacion_id', models.CharField(max_length=128)),
                ('estado_dir', models.CharField(max_length=50)),
                ('ciudad_dir', models.CharField(max_length=50)),
                ('cp_dir', models.CharField(max_length=5)),
                ('fecha_en_sistema', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='P_alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.CharField(max_length=128)),
                ('alergia_id', models.CharField(max_length=128)),
                ('citicidad', models.CharField(max_length=50)),
                ('codigo_sistema', models.CharField(max_length=150)),
                ('codigo_codigo', models.CharField(max_length=50)),
                ('codigo_visual', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=150)),
                ('estatus', models.CharField(max_length=50)),
                ('fecha_en_sistema', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='P_direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.CharField(max_length=128)),
                ('tipo_dir', models.CharField(max_length=50)),
                ('estado_dir', models.CharField(max_length=50)),
                ('ciudad_dir', models.CharField(max_length=50)),
                ('cp_dir', models.CharField(max_length=5)),
                ('fecha_en_sistema', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='P_encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.CharField(max_length=128)),
                ('encuentro_id', models.CharField(max_length=128)),
                ('estatus', models.CharField(max_length=50)),
                ('sistema', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50)),
                ('visual', models.CharField(max_length=50)),
                ('fecha_en_sistema', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='P_observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.CharField(max_length=128)),
                ('encuentro_id', models.CharField(max_length=128)),
                ('observacion_id', models.CharField(max_length=128)),
                ('codigo_sistema', models.CharField(max_length=150)),
                ('codigo_codigo', models.CharField(max_length=50)),
                ('codigo_visual', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=150)),
                ('cantidad_unidad', models.CharField(max_length=50)),
                ('cantidad_valor', models.CharField(max_length=50)),
                ('cantidad_codigo', models.CharField(max_length=50)),
                ('cantidad_sitema', models.CharField(max_length=150)),
                ('texto', models.CharField(max_length=150)),
                ('fecha_en_sistema', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('fecha_nac', models.DateField()),
                ('estado_nac', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(default='Desconocido', max_length=50)),
                ('sexo', models.CharField(max_length=2)),
                ('etnia', models.CharField(max_length=2)),
                ('genero', models.CharField(max_length=30)),
                ('tipo_sangre', models.CharField(max_length=2)),
                ('sangre_rh', models.CharField(max_length=8)),
                ('fecha_de_actualizacion', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
