# Generated by Django 4.1.2 on 2022-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_observacion',
            name='codigo_visual',
            field=models.CharField(max_length=150),
        ),
    ]
