# Generated by Django 4.1.2 on 2022-11-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repositorio', '0002_alter_p_observacion_codigo_visual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_observacion',
            old_name='texto',
            new_name='cantidad_texto',
        ),
        migrations.RenameField(
            model_name='p_observacion',
            old_name='valor',
            new_name='codigo_texto',
        ),
        migrations.AddField(
            model_name='p_observacion',
            name='estatus',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='p_observacion',
            name='tipo_valor',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
