# Generated by Django 4.1.2 on 2022-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repositorio', '0003_rename_texto_p_observacion_cantidad_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_observacion',
            name='cantidad_visual',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
